# --------------------------------------------------------------
# GNUmakefile for exotic models library. A.Bórquez 21-Apr-22.
# --------------------------------------------------------------

name := G4exotic_models

SUBDIRS = sexaquark

SUBLIBS = G4exotic_sexaquark

ifndef G4INSTALL
  G4INSTALL = ../../../..
endif

include $(G4INSTALL)/config/globlib.gmk
